#!/bin/bash

#!/bin/bash
#
# chkconfig: 345 80 20
# description: oracle database controls
#
# Control the startup and shutdown of databases referenced in the /etc/oratab
# file. Entries indicated with a 'Y' in the last column are only applicable for
# this service.
#
# The progress log for each database plus errors and warnings are logged in the
# $ORACLE_HOME directory named startup.log, shutdown.log, and listener.log.


# Configure the environment and include specific /etc/init.d script functions
. /etc/init.d/functions


# Additional PATH configuration
. /home/site/app/DynIP/etc/fcgi.env


start() {
    su $APP_OWNER -c "$APP_DIR/bin/start_fcgi.sh"
}

stop() {
    su $APP_OWNER -c "$APP_DIR/bin/stop_fcgi.sh"
}

status() {
    su $APP_OWNER -c "$APP_DIR/bin/status_fcgi.sh"
}


case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
        exit 1
        ;;
esac
